<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php
    $titles = array(
        '0' => 'Search',
        '3' => 'News',
        '5' => 'Archives',
        '6' => 'Heritage',
        '4' => 'Biographies',
        '12' => 'Documents',
        '2' => 'Events',
        '9' => 'Publications',
        '11' => 'Images',
        '10' => 'Researchers',
        'movie' => 'Movies',
        'picture' => 'Pictures',
        'poster' => 'Posters'
    );

    //var_dump($query);
    $template = 0;
    if(isset($query['resource_template_id'])):
        $template = preg_replace('/\D/', '', $query['resource_template_id']);
        if(is_array($template)):
            $template = $template[0];
        endif;
        //var_dump($template);
        if(!array_key_exists($template,$titles)):
            $template = 0;
        endif;
        if($template == 6 && isset($query['property'][0]['text'])):
            $template = $query['property'][0]['text'];
        endif;
    endif;
?>
  <nav class="breadcrumbs">
      <a href="<?php echo $site->url();?>">Home</a> -
      <?php echo $titles[$template];?>
  </nav>
  <div class="top">
    <?php if ($itemSetShow): ?>
        <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
        <h3><?php echo $translate('Item set'); ?></h3>
        <div class="metadata">
            <?php echo $itemSet->displayValues(); ?>
        </div>
        <div class="item-set-items">
        <?php echo '<h3>' . $escape($translate($titles[$template])) . '</h3>'; ?>
    <?php else: ?>
        <?php echo $this->pageTitle($translate($titles[$template]), 2); ?>
    <?php endif; ?>
  </div>

  <div class="results">
    <?php //echo $this->searchFilters(); ?>

    <div class="browse-controls">
        <?php echo $this->pagination(); ?>
        <?php //echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
        <?php echo $this->sortSelector($sortHeadings); ?>
    </div>

    <?php $this->trigger('view.browse.before'); ?>
    <ul class="resource-list">
    <?php
    foreach ($items as $item):
        $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
        $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
        $type = $item->resourceTemplate();
        if($type && $template):
          $type= $type->label();
        else:
          $type= "";
        endif;
    ?>
        <li class="item resource <?php echo $type;?>">
            <?php echo $item->linkRaw($this->thumbnail($item, 'square')); ?>
            <div class="description">
              <div class="heading">
                <h4><?php echo $item->link($heading); ?></h4>
              </div>
              <?php if($type == 'News' && $type != 'Event'):?>
                <div class="date"><?php echo $item->value('dcterms:date');?></div>                
              <?php endif;?>
              <?php if($type != 'Heritage' && $type != 'Publication'):?>
                <?php if ($body): ?>
                  <?php
                    $wrapped = wordwrap($body, 200, "\n", 1);
                    $lines = explode("\n", $wrapped);
                    (array_key_exists('1', $lines)) ? $suffix = '...' : $suffix = '';
                    $new_str = $lines[0] . $suffix;
                    echo $new_str;
                  ?>
                <?php endif; ?>
              <?php endif;?>
              <?php if($type == 'Publication'):?>
               <div class="browse-meta property">
                 <h4>Author</h4>
                 <div class="value"><?php echo $item->value('dcterms:creator');?></div>
               </div>
               <div class="browse-meta property">
                 <h4>Serie / periodical </h4>
                 <div class="value"><?php echo $item->value('dcterms:isPartOf');?></div>
               </div>
               <div class="browse-meta property">
                 <h4>Date </h4>
                 <div class="value"><?php echo $item->value('dcterms:date');?></div>
               </div>
               <div class="browse-meta property">
                 <h4>Pages</h4>
                 <div class="value"><?php echo $item->value('dcterms:extent');?></div>
               </div>
               <div class="browse-meta property">
                 <h4>ISBN/ISSN</h4>
                 <div class="value"><?php echo $item->value('dcterms:identifier');?></div>
               </div>
               <div class="browse-meta property">
                 <h4>Link</h4>
                 <div class="value"><a target="_blank" href="<?php echo $item->value('dcterms:relation');?>"><?php echo $item->value('dcterms:relation');?></a></div>
               </div>
            <?php endif;?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php echo ($itemSetShow) ? '</div>' : ''; ?>
    <?php $this->trigger('view.browse.after'); ?>
    <div class="browse-controls">
      <?php echo $this->pagination(); ?>
    </div>
  </div>
