<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();

if($template):
  $type = $template->label();
  $template = $template->id();
else:
  $type = "";
  $template = 0;
endif;
?>
<?php
    $titles = array(
        '0' => array('title' => 'Search', 'url' => '/item'),
        '3' => array('title' => 'News', 'url' => '/item?resource_template_id=3'),
        '5' => array('title' => 'Archives', 'url' => '/item?resource_template_id=5'),
        '6' => array('title' => 'Heritage', 'url' => '/page/heritage'),
        '4' => array('title' => 'Biographies', 'url' => '/item?resource_template_id=4'),
        '12' => array('title' => 'Documents', 'url' => '/item?resource_template_id=12'),
        '2' => array('title' => 'Events', 'url' => '/item?resource_template_id=2'),
        '9' => array('title' => 'Publications', 'url' => '/item?resource_template_id=9'),
        '11' => array('title' => 'Images', 'url' => '/item?resource_template_id=9'),
        '10' => array('title' => 'Researchers', 'url' => '/item?property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=researcher&resource_class_id[]=&resource_template_id[]=10&item_set_id[]=&site_id=&submit=Search'),
        'movie' => array('title' => 'Movies', 'url' => '/item?property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=movie&resource_class_id[]=&resource_template_id[]=6&item_set_id[]=&site_id=&submit=Search'),
        'picture' => array('title' => 'Pictures', 'url' => '/item?property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=picture&resource_class_id[]=&resource_template_id[]=6&item_set_id[]=&site_id=&submit=Search'),
        'poster' => array('title' => 'Posters', 'url' => '/item?property[0][joiner]=and&property[0][property]=8&property[0][type]=eq&property[0][text]=poster&resource_class_id[]=&resource_template_id[]=6&item_set_id[]=&site_id=&submit=Search')
    );

    //var_dump($query);
    if($template):
        //var_dump($template);
        if($template == 6 && $item->value('dcterms:type')):
            $template = strval($item->value('dcterms:type'));
        endif;
    endif;
?>
<nav class="breadcrumbs">
    <a href="<?php echo $site->url();?>">Home</a> -
    <a href="<?php echo $site->url().$titles[$template]['url'];?>"><?php echo $titles[$template]['title'];?></a> -
    <?php echo $item->displayTitle();?>
</nav>
<div class="top">
    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
</div>
<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<div class="metadata">
    <?php echo $item->displayValues(); ?>
</div>
<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
