version: '2'

services:
  
  omeka-s:    
    build: ./
    ports:
      - "9000:80"
    volumes:
      - ./modules/:/var/www/html/civitas/modules/
      - ./themes/:/var/www/html/civitas/themes/
      - ./files/:/var/www/html/civitas/files/
      - ./config/:/var/www/html/civitas/config/
      - ${PWD}/htaccess:/var/www/html/civitas..htaccess
      - ${PWD}/imagemagick-policy.xml:/var/www/html/civitas/imagemagick-policy.xml
    restart: always
