version: '2'

services:

  omeka-s:
    build: ./
    ports:
      - "9003:80"
    volumes:
      - ./modules/:/var/www/html/test/modules/
      - ./themes/:/var/www/html/test/themes/
      - ./files/:/var/www/html/test/files/
      - ./config/:/var/www/html/test/config/
      - ./htaccess:/var/www/html/test/.htaccess
      - ./imagemagick-policy.xml:/var/www/html/test/imagemagick-policy.xml
    restart: always
