<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>
<?php foreach ($values as $term => $propertyData): ?>
    <?php
      $dontshow = ['Title'];
      if(in_array($propertyData['property']->label(),$dontshow)):
        continue;
      endif;
    ?>
    <div class="property">
        <?php if($values):?>
          <h4>
          <?php if ($propertyData['alternate_label']): ?>
            <?php if ($propertyData['alternate_label'] != "nolabel"): ?>
              <?php echo $escape($propertyData['alternate_label']); ?>
            <?php endif; ?>
          <?php else: ?>
          <?php echo $escape($translate($propertyData['property']->label())); ?>
          <?php endif; ?>
          <?php if ('term' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
          <?php elseif ('vocab' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
          <?php endif; ?>
          </h4>
        <?php endif;?>
        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $string = $value->asHtml();
            $valueType = $value->type();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            if($term == "dcterms:relation"){

              $url = '@(http(s)?)?(://)?(([a-zA-Z])([-\w]+\.)+([^\s\.]+[^\s]*)+[^,.\s])@';
              $string = preg_replace($url, '<a href="http$2://$4" target="_blank" title="$0">$0</a>', $string);
              
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>

                <?php echo $string; ?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
