<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Serif+Pro:400,700|Source+Sans+Pro:300,400,600,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<!--<script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>-->
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <header>
            <!--<section class="top-nav-section">
              <div class="nav-top">

                  <ul>
                    <li><a href="">News</a></li>
                    <li><a href="">Events</a></li>
                    <li><a href="">About</a></li>
                    <li><a href="">Contact</a></li>
                  </ul>
                  <div id="search-top">
                      <?php echo $this->partial('common/search-form'); ?>
                  </div>

              </div>
            </section>-->
            <?php
              $url = $this->serverUrl(true);
              if (strpos($url, 'page/home') !== false) {
                  $home = true;
              }else{
                $home = false;
              }
            ?>

            <div class="header-container">
              <div class="logo">
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                <?php endif; ?>
              </div>

              <nav>
              <?php
              echo $site->publicNav()->menu()->renderMenu(null, [
                  'maxDepth' => $this->themeSetting('nav_depth') - 1
              ]);
              ?>
              <div id="search">
                  <?php echo $this->partial('common/search-form'); ?>
              </div>
              </nav>
              <!--<a class="search-toggle"><i class="fas fa-search"></i></a>-->

            </div>
        </header>
        <?php if($home):?>
        <section class="hero-section">
          <div class="hero">
            <div class="hero-container">
              <div class="slogan-container">
                <div class="slogan">
                  <p><span>CIVITAS</span> is a platform of archives and research on Christian Democracy in Europe and the world</p>
                  <a href="<?php echo $site->url(); ?>/page/about" class="more-link">Read more</a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <?php endif;?>
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer>
          <div class="footer-container">
            <div class="footer-text">
              <?php if ($footerContent = $this->themeSetting('footer')): ?>
              <?php echo $footerContent; ?>
              <?php else: ?>
                  <?php echo $this->translate('Powered by Omeka S'); ?>
              <?php endif; ?>
            </div>
          </div>
        </footer>
    </body>
</html>
