<div class="preview-block">
  <?php if ($this->heading): ?>
  <div class="top">
  <h3><?php echo $this->heading; ?><span class="more-preview">
    <?php
    if ($this->linkText):
        echo $this->hyperlink($this->linkText, $this->url(
            'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
        ));
    endif;
    ?>
  </span></h3></div>
  <?php endif; ?>
  <?php
    $size = 'square';
    $span = "preview-item-".(12 / sizeof($this->resources));
    if($span < 6):
      $size = 'square';
    else:
      $size = 'large';
    endif;
  ?>
  <div class="resource-list preview ">
    <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

      foreach ($this->resources as $resource):
          $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
          $body = $resource->value($bodyTerm);
          $media = $resource->primaryMedia()->thumbnailUrl($size);
    ?>
      <div class="<?php echo $this->resourceType; ?> resource <?php echo $span;?>">
        <div class="event-img"  style="background: center / cover no-repeat url(<?php echo $media;?>)">
          <div class="event-text">
            <h4><?php echo $resource->link($heading); ?></h4>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
</div>
